In [101]:
#Import libraries
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from scipy.stats import *
from sklearn import *
from sklearn import preprocessing
from sklearn.preprocessing import PolynomialFeatures
from sklearn import metrics
from sklearn import datasets
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn import svm, datasets,metrics
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
#from sklearn.grid_search import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import learning_curve
from scipy.stats import randint as sp_randint

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score

from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO  
from IPython.display import Image  
import pydotplus


In [103]:
label = LabelEncoder()
data = pd.read_excel("testInt.xlsx",header=None)


X = data.iloc[:,:-2].values
y = data.iloc[:,-2].values
X = X.astype('int')
y = y.astype('int')

print(X)
print(y)

[[55572   165   158]
 [50563   164   157]
 [42842   164   157]
 ...
 [ 2665  2222  2085]
 [ 2657  2216  2079]
 [ 2639  2204  2066]]
[ 1  1  1 ... 10 10 10]


# Decision Tree Classification

In [117]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test

# Create Decision Tree classifer object
tree = DecisionTreeClassifier(random_state=0)
#tree = DecisionTreeClassifier(criterion="entropy", max_depth=3)

# Train Decision Tree Classifer
tree = tree.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = tree.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))



#score_tr = cross_val_score(tree, X, y, cv=50,scoring='accuracy')
#print("Accuracy of Decision Tree: " + str(score_tr.mean()))

Accuracy: 0.44561933534743203


# Decision Tree Regression

In [119]:
label = LabelEncoder()
data = pd.read_excel("testInt.xlsx",header=None)


X = data.iloc[:,:-1].values
#for i in range(X.shape[1]):
#    X[:,i] = label.fit_transform(X[:,i])
#y = data.iloc[:,-1].values

y = data.iloc[:,-1].values
X = X.astype('int')
y = y.astype('int')

#X = [round(X) for X in X]

#y = [round(y) for y in y]

#y = label.fit_transform(y)
print(X)
print(y)

[[55572   165   158     1]
 [50563   164   157     1]
 [42842   164   157     1]
 ...
 [ 2665  2222  2085    10]
 [ 2657  2216  2079    10]
 [ 2639  2204  2066    10]]
[  4   4   5 ... 147 148 148]


In [120]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test

# Create Decision Tree classifer object
tree = DecisionTreeClassifier(random_state=0)
#tree = DecisionTreeClassifier(criterion="entropy", max_depth=3)

# Train Decision Tree Classifer
tree = tree.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = tree.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))



#score_tr = cross_val_score(tree, X, y, cv=50,scoring='accuracy')
#print("Accuracy of Decision Tree: " + str(score_tr.mean()))

Accuracy: 0.44561933534743203


# Random Forest Classification

In [133]:
label = LabelEncoder()
data = pd.read_excel("testInt.xlsx",header=None)


X = data.iloc[:,:-2].values
#for i in range(X.shape[1]):
#    X[:,i] = label.fit_transform(X[:,i])
#y = data.iloc[:,-1].values

y = data.iloc[:,-2].values
X = X.astype('int')
y = y.astype('int')

#X = [round(X) for X in X]

#y = [round(y) for y in y]

#y = label.fit_transform(y)
print(X)
print(y)

[[55572   165   158]
 [50563   164   157]
 [42842   164   157]
 ...
 [ 2665  2222  2085]
 [ 2657  2216  2079]
 [ 2639  2204  2066]]
[ 1  1  1 ... 10 10 10]


In [134]:
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9909365558912386


# Random Tree Regression 

In [137]:
label = LabelEncoder()
data = pd.read_excel("testInt.xlsx",header=None)


X = data.iloc[:,:-1].values
#for i in range(X.shape[1]):
#    X[:,i] = label.fit_transform(X[:,i])
#y = data.iloc[:,-1].values

y = data.iloc[:,-1].values
X = X.astype('int')
y = y.astype('int')

#X = [round(X) for X in X]

#y = [round(y) for y in y]

#y = label.fit_transform(y)
print(X)
print(y)

[[55572   165   158     1]
 [50563   164   157     1]
 [42842   164   157     1]
 ...
 [ 2665  2222  2085    10]
 [ 2657  2216  2079    10]
 [ 2639  2204  2066    10]]
[  4   4   5 ... 147 148 148]


In [138]:
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.472809667673716
